<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4e457fa4df0143680f63e3021527c69e
{
    public static $prefixLengthsPsr4 = array (
        'M' =>
        array (
            'Magnetis\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Magnetis\\' =>
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Magnetis\\Features\\MagnetisModule' => __DIR__ . '/../..' . '/src/Features/MagnetisModule.php',
        'Magnetis\\Interfaces\\Feature' => __DIR__ . '/../..' . '/src/Interfaces/Feature.php',
        'Magnetis\\MagnetisPlugin' => __DIR__ . '/../..' . '/src/MagnetisPlugin.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4e457fa4df0143680f63e3021527c69e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4e457fa4df0143680f63e3021527c69e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit4e457fa4df0143680f63e3021527c69e::$classMap;

        }, null, ClassLoader::class);
    }
}
