<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Magnetis\\Features\\MagnetisModule' => $baseDir . '/src/Features/MagnetisModule.php',
    'Magnetis\\Interfaces\\Feature' => $baseDir . '/src/Interfaces/Feature.php',
    'Magnetis\\MagnetisPlugin' => $baseDir . '/src/MagnetisPlugin.php',
);
